/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentistfinder;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Relax
 */
public class AddressForm extends javax.swing.JFrame {
    private ArrayList<String> personalData;
    private ArrayList<Education> eduList;
    private ArrayList<Address> addList=new ArrayList<>();
    private DefaultListModel listModel= new DefaultListModel();
    private EducationForm preForm;
    private SpecializationForm nextForm;
    public void setPerData(ArrayList<String> personalData)
    {
        this.personalData=personalData;
    }
     public void setEduData(ArrayList<Education> eduList)
    {
        this.eduList=eduList;
    }
    /**
     * Creates new form AddressForm
     */
    public AddressForm(ArrayList<String> personalData,ArrayList<Education> eduList , EducationForm preForm) {
        this.personalData=personalData;
        this.eduList=eduList;
        this.preForm=preForm;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addForm_country = new javax.swing.JTextField();
        addForm_city = new javax.swing.JTextField();
        addForm_addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addForm_list = new javax.swing.JList<>();
        addForm_removeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addForm_state = new javax.swing.JTextField();
        addForm_postalCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addForm_nextBtn = new javax.swing.JButton();
        addForm_backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Address Section"));

        jLabel3.setText("Country");

        jLabel4.setText("City");

        addForm_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addForm_countryActionPerformed(evt);
            }
        });

        addForm_addBtn.setText("Add");
        addForm_addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addForm_addBtnActionPerformed(evt);
            }
        });

        addForm_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                addForm_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(addForm_list);

        addForm_removeBtn.setText("Remove");
        addForm_removeBtn.setEnabled(false);
        addForm_removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addForm_removeBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("State");

        jLabel2.setText("Postal Code");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addForm_country, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addForm_city, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addForm_removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addForm_addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addForm_state, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addForm_postalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addForm_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addForm_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addForm_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addForm_postalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(addForm_addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addForm_removeBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addForm_nextBtn.setText("Next");
        addForm_nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addForm_nextBtnActionPerformed(evt);
            }
        });

        addForm_backBtn.setText("Back");
        addForm_backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addForm_backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addForm_backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addForm_nextBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addForm_nextBtn)
                    .addComponent(addForm_backBtn))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addForm_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addForm_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addForm_countryActionPerformed

    private void addForm_addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addForm_addBtnActionPerformed

        listModel.addElement((addForm_country.getText()+ " - "+addForm_city.getText()));
        addList.add(new Address(addForm_country.getText(),addForm_state.getText(), addForm_city.getText(), addForm_postalCode.getText()));
        addForm_list.setModel(listModel);
        clearFields();

    }//GEN-LAST:event_addForm_addBtnActionPerformed

    private void addForm_backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addForm_backBtnActionPerformed

        this.setVisible(false);
        preForm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addForm_backBtnActionPerformed

    private void addForm_nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addForm_nextBtnActionPerformed
        
        if(nextForm==null)
            nextForm=new SpecializationForm(personalData, eduList, addList, this);
        else
        {
            nextForm.setPreData(personalData);
            nextForm.setPreEduList(eduList);
            nextForm.setPreAddList(addList);
        }
        nextForm.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_addForm_nextBtnActionPerformed

    private void addForm_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_addForm_listValueChanged

           addForm_removeBtn.setEnabled(! addForm_list.isSelectionEmpty());
        // TODO add your handling code here:
    }//GEN-LAST:event_addForm_listValueChanged

    private void addForm_removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addForm_removeBtnActionPerformed
        int indx=addForm_list.getSelectedIndex();
        addList.remove(indx);
        listModel.remove(indx);
        // TODO add your handling code here:
    }//GEN-LAST:event_addForm_removeBtnActionPerformed
   private void clearFields()
    {
        addForm_country.setText(null);
        addForm_city.setText(null);
        addForm_state.setText(null);
        addForm_postalCode.setText(null);

    }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addForm_addBtn;
    private javax.swing.JButton addForm_backBtn;
    private javax.swing.JTextField addForm_city;
    private javax.swing.JTextField addForm_country;
    private javax.swing.JList<String> addForm_list;
    private javax.swing.JButton addForm_nextBtn;
    private javax.swing.JTextField addForm_postalCode;
    private javax.swing.JButton addForm_removeBtn;
    private javax.swing.JTextField addForm_state;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
