/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentistfinder;

/**
 *
 * @author Relax
 */
public class AddressPanel extends javax.swing.JPanel{

    /**
     * Creates new form AddresspPanel
     */
    public AddressPanel(Address add) {
        initComponents();
        this.city.setText(add.getCity());
        this.country.setText(add.getCountry());
        this.state.setText(add.getState());
        this.postalcode.setText(add.getPostalCode());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        postalcode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        state = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Country");
        add(jLabel1);
        add(country);

        jLabel3.setText("City");
        add(jLabel3);
        add(city);

        jLabel4.setText("Postal Code");
        add(jLabel4);
        add(postalcode);

        jLabel2.setText("State");
        add(jLabel2);
        add(state);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    private javax.swing.JLabel country;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel postalcode;
    private javax.swing.JLabel state;
    // End of variables declaration//GEN-END:variables
}
