/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentistfinder;

/**
 *
 * @author Relax
 */
public class EducationPanel extends javax.swing.JPanel {

    /**
     * Creates new form EducationPanel
     */
    public EducationPanel(Education x) {
        
        initComponents();
        this.year.setText(x.getYear());
        this.degree.setText(x.getDegree());
        this.major.setText(x.getMajor());
        this.school.setText(x.getSchool());
        this.setVisible(true);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        degree = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        school = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        major = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Degree");
        add(jLabel1);
        add(degree);

        jLabel2.setText("Year");
        add(jLabel2);
        add(year);

        jLabel4.setText("School");
        add(jLabel4);
        add(school);

        jLabel3.setText("Major");
        add(jLabel3);
        add(major);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel degree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel major;
    private javax.swing.JLabel school;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
