/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentistfinder;

import java.awt.Component;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Relax
 */
public class PreviewForm extends javax.swing.JFrame {
private Dentist dentist;
    /**
     * Creates new form PreviewForm
     */
    private void AddeduPanelstoPanel(javax.swing.JPanel panel,javax.swing.JPanel panel2,ArrayList<Education> panels,ArrayList<Address> panels2)
    {
        GridLayout xx= (GridLayout) panel.getLayout();
        xx.setRows(panels.size());
        panel.setLayout(xx);
         for(int i=0;i<panels.size();i++)
         {
             EducationPanel x = new EducationPanel(panels.get(i));
             x.setBounds(20+(x.preferredSize().width*i), 4, x.preferredSize().width ,   x.preferredSize().height );
             panel.add(x);
         }
        GridLayout xxx= (GridLayout) panel2.getLayout();
        xxx.setRows(panels2.size());
        panel.setLayout(xxx);
         for(int i=0;i<panels2.size();i++)
         {
             AddressPanel x = new AddressPanel(panels2.get(i));
             x.setBounds(20+(x.preferredSize().width*i), 4, x.preferredSize().width ,   x.preferredSize().height );
             panel2.add(x);
         }
         if (panels.size()==0)
             jScrollPane1.setVisible(false);
         if (panels2.size()==0)
             jScrollPane2.setVisible(false);
        
    }
    public PreviewForm(Dentist dentist) 
    {        
        initComponents();
        
        add(new EducationPanel(new Education("1", "2", null, null)));
        AddeduPanelstoPanel(eduPanel,addPanel,dentist.getEduList(),dentist.getAddList());
        this.dentist=dentist;
        prevForm_fullName.setText(dentist.getFirst_name()+" " + dentist.getLast_name());
        String optionalData=dentist.getEmail() + (dentist.getEmail().isEmpty()==false?"| ":"");
               optionalData+=dentist.getPhoneNumber()+ (dentist.getPhoneNumber().isEmpty()==false?"| ":"");
               optionalData+=dentist.getWebsite();
               prevForm_LN.setText(dentist.getLicenseNumber());
               prevForm_year.setText(dentist.getLearsinPractice());
               prevForm_gender.setText(dentist.getGender());
               prevForm_lCountry.setText(dentist.getLCN());
               prevForm_perInfo.setText(optionalData);
               if(dentist.getIsSpecialist())
               {
                    GridLayout xx= (GridLayout) specPanel.getLayout();
                    xx.setRows(dentist.getSpecializationsList().size());
                    specPanel.setLayout(xx);
                     for(int i=0;i<dentist.getSpecializationsList().size();i++)
                     {
                         SpecilizationPanel x = new SpecilizationPanel(dentist.getSpecializationsList().get(i));
                         x.setBounds(20+(x.preferredSize().width*i), 4, x.preferredSize().width ,   x.preferredSize().height );
                         specPanel.add(x);
         }
                   if(dentist.getSpecializationsList().size()==0)
                       SpecSPanel.setVisible(false);
                   
               }
                    setVisible(true);


    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prevForm_fullName = new javax.swing.JLabel();
        prevForm_perInfo = new javax.swing.JLabel();
        bioPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        prevForm_lCountry = new javax.swing.JLabel();
        prevForm_LN = new javax.swing.JLabel();
        prevForm_year = new javax.swing.JLabel();
        prevForm_gender = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eduPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        SpecSPanel = new javax.swing.JScrollPane();
        specPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prevForm_fullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        bioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Biography Information"));

        jLabel15.setText("License Country:");

        jLabel16.setText("License Number");

        jLabel17.setText("Years in Practice");

        jLabel18.setText("Gender");

        javax.swing.GroupLayout bioPanelLayout = new javax.swing.GroupLayout(bioPanel);
        bioPanel.setLayout(bioPanelLayout);
        bioPanelLayout.setHorizontalGroup(
            bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bioPanelLayout.createSequentialGroup()
                        .addComponent(prevForm_year, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prevForm_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bioPanelLayout.createSequentialGroup()
                        .addGroup(bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prevForm_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prevForm_lCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        bioPanelLayout.setVerticalGroup(
            bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prevForm_lCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prevForm_LN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18))
                    .addComponent(prevForm_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevForm_year, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Education"));

        eduPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        eduPanel.setLayout(new java.awt.GridLayout(100, 1));
        jScrollPane1.setViewportView(eduPanel);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

        addPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addPanel.setLayout(new java.awt.GridLayout(100, 1));
        jScrollPane2.setViewportView(addPanel);

        jButton1.setText("Widget");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SpecSPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Specilization"));

        specPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        specPanel.setLayout(new java.awt.GridLayout(100, 1));
        SpecSPanel.setViewportView(specPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(prevForm_perInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prevForm_fullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SpecSPanel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prevForm_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prevForm_perInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpecSPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    new Widget(prevForm_fullName.getText(),prevForm_perInfo.getText(),((dentist.getAddList()!=null && !dentist.getAddList().isEmpty())?dentist.getAddList().get(0).toString():null),((dentist.getEduList()!=null && !dentist.getEduList().isEmpty())?dentist.getEduList().get(0).getMajor():"")).setVisible(true);
    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SpecSPanel;
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel bioPanel;
    private javax.swing.JPanel eduPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel prevForm_LN;
    private javax.swing.JLabel prevForm_fullName;
    private javax.swing.JLabel prevForm_gender;
    private javax.swing.JLabel prevForm_lCountry;
    private javax.swing.JLabel prevForm_perInfo;
    private javax.swing.JLabel prevForm_year;
    private javax.swing.JPanel specPanel;
    // End of variables declaration//GEN-END:variables
}
