/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentistfinder;

/**
 *
 * @author Relax
 */
public class SpecilizationPanel extends javax.swing.JPanel {

    /**
     * Creates new form SpecilizationPanel
     */
    public SpecilizationPanel(Specialization spec) {
        initComponents();
        sYear.setText(spec.getYear());
        aOS.setText(spec.getAreaOfSpecialization());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aOS = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sYear = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.GridLayout(2, 2));

        aOS.setText("Area of Specilization");
        add(aOS);
        add(jLabel2);

        sYear.setText("Start Year");
        add(sYear);
        add(jLabel4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aOS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel sYear;
    // End of variables declaration//GEN-END:variables
}
