/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentistfinder;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Relax
 */
public class SpecializationForm extends javax.swing.JFrame {

    private ArrayList<String> preData;
    private ArrayList<Education> preEduList;
    private ArrayList<Address> preAddList;
    private ArrayList<Specialization> specList=new ArrayList<Specialization>();
    private DefaultListModel listModel= new DefaultListModel();
    private AddressForm preForm;

    public void setPreData(ArrayList<String> preData) {
        this.preData = preData;
    }

    public void setPreEduList(ArrayList<Education> preEduList) {
        this.preEduList = preEduList;
    }

    public void setPreAddList(ArrayList<Address> preAddList) {
        this.preAddList = preAddList;
    }

    /**
     * Creates new form SpecializationForm
     */
    public SpecializationForm(ArrayList<String> preData,ArrayList<Education> preEduList,ArrayList<Address> preAddList,AddressForm preForm) {
        this.preData=preData;
        this.preAddList=preAddList;
        this.preForm=preForm;
        this.preEduList=preEduList;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        speaclizeForm_startYear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        specialForm_aOS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        specialForm_list = new javax.swing.JList<>();
        specialForm_addBtn = new javax.swing.JButton();
        specialForm_removeBtn = new javax.swing.JButton();
        spealizeForm_isSpecialCheckBox = new javax.swing.JCheckBox();
        speciForm_confirm = new javax.swing.JButton();
        speciForm_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ٍSpecialization Section"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Specialist Information"));

        speaclizeForm_startYear.setEnabled(false);

        jLabel2.setText("Start Year");

        specialForm_aOS.setEnabled(false);
        specialForm_aOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialForm_aOSActionPerformed(evt);
            }
        });

        jLabel3.setText("Area of specialization");

        specialForm_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        specialForm_list.setEnabled(false);
        specialForm_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                specialForm_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(specialForm_list);

        specialForm_addBtn.setText("Add");
        specialForm_addBtn.setEnabled(false);
        specialForm_addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialForm_addBtnActionPerformed(evt);
            }
        });

        specialForm_removeBtn.setText("Remove");
        specialForm_removeBtn.setEnabled(false);
        specialForm_removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialForm_removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(specialForm_removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(specialForm_addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speaclizeForm_startYear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialForm_aOS, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(specialForm_aOS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speaclizeForm_startYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(specialForm_addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(specialForm_removeBtn))))
        );

        spealizeForm_isSpecialCheckBox.setText("Is Specialist");
        spealizeForm_isSpecialCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spealizeForm_isSpecialCheckBoxActionPerformed(evt);
            }
        });

        speciForm_confirm.setText("Confirm");
        speciForm_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speciForm_confirmActionPerformed(evt);
            }
        });

        speciForm_back.setText("Back");
        speciForm_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speciForm_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(speciForm_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(speciForm_confirm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spealizeForm_isSpecialCheckBox))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(spealizeForm_isSpecialCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speciForm_confirm)
                    .addComponent(speciForm_back))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void specialForm_aOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialForm_aOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialForm_aOSActionPerformed

    private void specialForm_addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialForm_addBtnActionPerformed

        specList.add(new Specialization(specialForm_aOS.getText(), speaclizeForm_startYear.getText()) );
        listModel.addElement((specialForm_aOS.getText()+ " - "+speaclizeForm_startYear.getText()));
        specialForm_list.setModel(listModel);
        
        clearFields();

    }//GEN-LAST:event_specialForm_addBtnActionPerformed

    private void spealizeForm_isSpecialCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spealizeForm_isSpecialCheckBoxActionPerformed

            speaclizeForm_startYear.setEnabled((spealizeForm_isSpecialCheckBox.isSelected()));
            specialForm_aOS.setEnabled((spealizeForm_isSpecialCheckBox.isSelected()));
            specialForm_list.setEnabled((spealizeForm_isSpecialCheckBox.isSelected()));
            specialForm_addBtn.setEnabled(spealizeForm_isSpecialCheckBox.isSelected());
    }//GEN-LAST:event_spealizeForm_isSpecialCheckBoxActionPerformed

    private void specialForm_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_specialForm_listValueChanged
       
            specialForm_removeBtn.setEnabled(!specialForm_list.isSelectionEmpty());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_specialForm_listValueChanged

    private void specialForm_removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialForm_removeBtnActionPerformed

        int indx=specialForm_list.getSelectedIndex();
        specList.remove(indx);
        listModel.remove(indx);
        // TODO add your handling code here:
    }//GEN-LAST:event_specialForm_removeBtnActionPerformed

    private void speciForm_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speciForm_backActionPerformed
            this.setVisible(false);
            preForm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_speciForm_backActionPerformed

    private void speciForm_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speciForm_confirmActionPerformed
            Builder builder;
           if(spealizeForm_isSpecialCheckBox.isSelected())
           {
               builder  = new DentistSpecialistBuilder();
               builder.setSpecializationsList(specList);
           }else
               builder=new DentistNonSpecialistBuilder();
           
            builder.setEduList(preEduList);
            builder.setAdressList(preAddList);
            builder.setFirstName(preData.get(0));
            builder.setLasttName(preData.get(1));
            builder.setEmail(preData.get(2));
            builder.setWebsite(preData.get(3));
            builder.setPhoneNumber(preData.get(4));
            builder.setGender(preData.get(5));
            builder.setLCN(preData.get(6));
            builder.setlicenseNumber(preData.get(7));
            builder.setlearsinPractice(preData.get(8));
            
            new PreviewForm(builder.getResult());
        // TODO add your handling code here:
    }//GEN-LAST:event_speciForm_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField speaclizeForm_startYear;
    private javax.swing.JCheckBox spealizeForm_isSpecialCheckBox;
    private javax.swing.JButton speciForm_back;
    private javax.swing.JButton speciForm_confirm;
    private javax.swing.JTextField specialForm_aOS;
    private javax.swing.JButton specialForm_addBtn;
    private javax.swing.JList<String> specialForm_list;
    private javax.swing.JButton specialForm_removeBtn;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        speaclizeForm_startYear.setText(null);
        specialForm_aOS.setText(null);
    }
}
